### ISSUE TITLE
Building for Risc-V is cumbersome

### ISSUE THREAD

**Issue by jorolf** [Amanieu/mini-backtrace#3]
Hi, I'm currently working on an embedded project using a synthesized RISCV Processor on an FPGA board and I'm having trouble building a binary. (The target triple is `riscv32i-unknown-none-elf`)

The first issue I ran into is the build script failing to find tools. It tries to find `riscv32-unknown-elf-g++` which doesn't work because I don't have it installed. I do however have clang installed which I can force it to use using environment variables.
```
CXX_riscv32i_unknown_none_elf=clang++
```
Then it fails because rust and clang use different target triples. (See https://github.com/rust-lang/rust-bindgen/issues/2136)
So I explicitly set it:
```
CXX_riscv32i_unknown_none_elf=clang++ 
CXXFLAGS_riscv32i_unknown_none_elf=--target=riscv32-unknown-none-elf
```
Then `bindgen` complains due to the same problem. (Until now the problem was `cc`)
```
CXX_riscv32i_unknown_none_elf=clang++ 
CXXFLAGS_riscv32i_unknown_none_elf=--target=riscv32-unknown-none-elf
BINDGEN_EXTRA_CLANG_ARGS_riscv32i_unknown_none_elf=--target=riscv32-unknown-none-elf
```
Finally the build script is executed without problems! But now the linker complains:
```
rust-lld: error: unknown argument '-Wl,eh_frame.ld'
```
In my `.cargo/config` I added a section for rustflags: (I already had some linker scripts for memory regions)
```toml
[target.riscv32i-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "force-unwind-tables",
  "-C", "link-arg=-Wl,eh_frame.ld"
]
```
Okay, maybe the syntax changed. So I tried `link-arg=-Teh_frame.ld` at which point it finally builds.

Is this the intended solution? Or are there other ways to make this easier? I already have a script which builds and synthesizes my project, adding these env variables isn't *that* bad however it still seems a bit too much to simply build this crate?

PS:
I also tried building on Windows which is why I wanted to use clang in the first place. (GCC on Windows is a can of worms I wanted to avoid.) There it fails because of a missing `ar` program. On linux it simply uses the GNU ar whereas on Windows I had to specifically tell it to use `llvm-ar`. This is probably a problem with the `cc` crate and not this one?

**Comment by Amanieu** [comment]
These issues are not specific to this crate and should be reported to cc/bindgen instead.

The latest version of the `cc` crate should help a bit with this: https://github.com/rust-lang/cc-rs/pull/993

**Comment by jorolf** [comment]
That's great to hear. I updated `cc` and now the target triple is detected correctly. However it still tries to find `riscv32-unknown-elf-g++`: `Failed to run: "riscv32-unknown-elf-g++" "--version"`
Does an issue already exist for that or should I create one? `cc` apparently just defaults to gcc if the target doesn't contain "llvm"? https://github.com/rust-lang/cc-rs/blob/df6262531e9e00a1e3cb6e4f69769eaf8dc06e58/src/lib.rs#L2796

It also seems like bindgen already has a bunch of exceptions, not for `riscv32i` though... 
https://github.com/rust-lang/rust-bindgen/blob/b5a6813c9a6feaeda38d7c672a1ed155f9e27266/bindgen/lib.rs#L688

**Comment by Amanieu** [comment]
You will need to use an environment variable to force `cc` to use clang, there's no way around that.

For bindgen you should submit a PR to add the missing support for `riscv32i`.

**Comment by jorolf** [comment]
My PR for rust-bindgen has been merged: https://github.com/rust-lang/rust-bindgen/pull/2808
